services:
  postgres:
    container_name: postgres-database
    image: postgres:latest
    environment:
      - POSTGRES_DB=rock-paper-scissors-db
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=#3q/^-!G212n4U10~t
    ports:
      - "5432:5432"
    volumes:
      - ./postgresql/data:/var/lib/postgresql/data