services:
  rock-paper-scissors-server:
    container_name: rock-paper-scissors-server
    build:
      dockerfile: Dockerfile
    image: rock-paper-scissors:latest
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-database:5432/rock-paper-scissors-db
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=#3q/^-!G212n4U10~t
    ports:
      - "8080:8080"
    networks:
      - spring-cloud-network
  postgres:
    container_name: postgres-database
    image: postgres:latest
    environment:
      - POSTGRES_DB=rock-paper-scissors-db
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=#3q/^-!G212n4U10~t
    ports:
      - "5432:5432"
    volumes:
      - ./postgresql/data:/var/lib/postgresql/data
    networks:
      - spring-cloud-network
networks:
  spring-cloud-network:
    driver: bridge